### PR TITLE
two offsets are wrong. I think kopen doesn't work.

### PR DESCRIPTION
**Pull request by m1zole**

### CODE REVIEW

**Comment by 34306** [comment]
how did you find 2 of them? I was thinking it will be the same but nah...

**Comment by 34306** [comment]
ah i saw that opa link. tysm

**Comment by m1zole** [comment]
If possible, could you help me?
Now, setuid(0) is working  but I can’t escape from sandbox.  
https://github.com/m1zole/kfd/blob/arm64/kfd/fun/sandbox.m#L24

**Comment by m1zole** [comment]
thank you!
I think you can get an raw kernel with
pzb -g kernelcache.release.n71 [ipsw url] &&  pyimg4 im4p extract -i ./kernelcache.release.n71 -o ./kernch

**Comment by 34306** [comment]
> thank you!
> I think you can get an raw kernel with
> pzb -g kernelcache.release.n71 [ipsw url] && pyimg4 im4p extract -i ./kernelcache.release.n71 -o ./kernch

I didn't know we can extract only kernel cache from a whole ipsw 😂
Usually download the whole ipsw and extract normally by hand xD
Btw ty!

**Pull request merged**
